declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  type LucideIcon = FC<SVGProps<SVGSVGElement> & { size?: number | string; strokeWidth?: number | string }>
  export const Activity: LucideIcon
  export const AlertCircle: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowRight: LucideIcon
  export const BarChart2: LucideIcon
  export const Bell: LucideIcon
  export const Building2: LucideIcon
  export const Calendar: LucideIcon
  export const Check: LucideIcon
  export const CheckCircle: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronRight: LucideIcon
  export const ClipboardList: LucideIcon
  export const Clock: LucideIcon
  export const Cpu: LucideIcon
  export const Download: LucideIcon
  export const Edit: LucideIcon
  export const Eye: LucideIcon
  export const FileText: LucideIcon
  export const Filter: LucideIcon
  export const Gauge: LucideIcon
  export const Heart: LucideIcon
  export const Home: LucideIcon
  export const Layout: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const Loader2: LucideIcon
  export const LogOut: LucideIcon
  export const Map: LucideIcon
  export const MapPin: LucideIcon
  export const Menu: LucideIcon
  export const Monitor: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const Package: LucideIcon
  export const Plus: LucideIcon
  export const RefreshCw: LucideIcon
  export const Search: LucideIcon
  export const Settings: LucideIcon
  export const Shield: LucideIcon
  export const ShieldCheck: LucideIcon
  export const Stethoscope: LucideIcon
  export const Trash2: LucideIcon
  export const TrendingUp: LucideIcon
  export const User: LucideIcon
  export const UserCheck: LucideIcon
  export const Users: LucideIcon
  export const UserPlus: LucideIcon
  export const X: LucideIcon
  export const XCircle: LucideIcon
  export const Zap: LucideIcon
  export const AlertTriangle: LucideIcon
  export const BarChart3: LucideIcon
  export const FileDown: LucideIcon
  export const Ruler: LucideIcon
  export const Scale: LucideIcon
  export const UserCog: LucideIcon
  export const Battery: LucideIcon
  export const HardDrive: LucideIcon
  export const Tablet: LucideIcon
  export const Droplets: LucideIcon
  export const Pencil: LucideIcon
  export const Usb: LucideIcon
  export const Bluetooth: LucideIcon
  export const Wifi: LucideIcon
  export const Phone: LucideIcon
  export const Mail: LucideIcon
}
